crm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('service_list', views.service_list, name='service_list'),
    path('service/create/', views.service_new, name='service_new'),
    path('service/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('service/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('product_list', views.product_list, name='product_list'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('customer/<int:pk>/summary/', views.summary, name='summary'),

]

mfscrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

crm/models.py
from django.utils import timezone
from django.db import models


# Create your models here.
class Customer(models.Model):
    cust_name = models.CharField(max_length=50)
    organization = models.CharField(max_length=100, blank=True)
    role = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    bldgroom = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    account_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_name)


class Service(models.Model):
    cust_name = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='services')
    service_category = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=200)
    setup_time = models.DateTimeField(
        default=timezone.now)
    cleanup_time = models.DateTimeField(
        default=timezone.now)
    service_charge = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_name)


class Product(models.Model):
    cust_name = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='products')
    product = models.CharField(max_length=100)
    p_description = models.TextField()
    quantity = models.IntegerField()
    pickup_time = models.DateTimeField(
        default=timezone.now)
    charge = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_name)

crm/forms.py
from django import forms
from .models import Customer, Service, Product


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_name', 'organization', 'role', 'bldgroom', 'account_number', 'address',
                  'city', 'state', 'zipcode', 'email', 'phone_number')


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = (
            'cust_name', 'service_category', 'description', 'location', 'setup_time', 'cleanup_time', 'service_charge')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'cust_name', 'product', 'p_description', 'quantity', 'pickup_time', 'charge', 'created_date',)

crm/views.py
from asyncio import Task

from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render
from .models import *
from .forms import *

from .models import Product

now = timezone.now()


def home(request):
    return render(request, 'crm/home.html',
                  {'crm': home})


@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/customer_list.html',
                  {'customers': customer})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/customer_list.html',
                          {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'crm/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('crm:customer_list')


@login_required
def service_list(request):
    services = Service.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/service_list.html', {'services': services})


@login_required
def service_new(request):
    if request.method == "POST":
        form = ServiceForm(request.POST)
        if form.is_valid():
            service = form.save(commit=False)
            service.created_date = timezone.now()
            service.save()
            services = Service.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/service_list.html',
                          {'services': services})
    else:
        form = ServiceForm()
        # print("Else")
    return render(request, 'crm/service_new.html', {'form': form})


@login_required
def service_edit(request, pk):
    service = get_object_or_404(Service, pk=pk)
    if request.method == "POST":
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            service = form.save()
            # service.customer = service.id
            service.updated_date = timezone.now()
            service.save()
            services = Service.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/service_list.html', {'services': services})
    else:
        # print("else")
        form = ServiceForm(instance=service)
    return render(request, 'crm/service_edit.html', {'form': form})


@login_required
def service_delete(request, pk):
    service = get_object_or_404(Customer, pk=pk)
    service.delete()
    return redirect('crm:service_list')


@login_required
def product_list(request):
    products = Product.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/product_list.html', {'products': products})


@login_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            products = Product.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/product_list.html',
                          {'products': products})
    else:
        form = ProductForm()
        # print("Else")
    return render(request, 'crm/product_new.html', {'form': form})


@login_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            product.updated_date = timezone.now()
            product.save()
            products = Product.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/product_list.html', {'products': products})
    else:
        # print("else")
        form = ProductForm(instance=product)
    return render(request, 'crm/product_edit.html', {'form': form})


@login_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return redirect('crm:product_list')





@login_required
def summary(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    services = Service.objects.filter(cust_name=pk)
    products = Product.objects.filter(cust_name=pk)
    sum_service_charge = Service.objects.filter(cust_name=pk).aggregate(Sum('service_charge'))
    sum_product_charge = Product.objects.filter(cust_name=pk).aggregate(Sum('charge'))
    # total = aggregate(Sum('sum_service_charge', 'sum_product_charge'))
    return render(request, 'crm/summary.html', {'customers': customers,
                                                'products': products,
                                                'services': services,
                                                'sum_service_charge': sum_service_charge,
                                                'sum_product_charge': sum_product_charge,})

crm/templates/crm/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>Maverick Food Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Maverick Food Service
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'crm:home' %}">Home</a></li>
                <li><a href="{% url 'crm:customer_list' %}">Customers</a></li>
               <li><a href="{% url 'crm:service_list' %}">Services</a></li>
                <li><a href="{% url 'crm:product_list' %}">Products</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                <div class="caption">
                                    <h2>Customer</h2>
                                    <p>Delighting customers and giving them a great dining experience is our main goal. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'crm:customer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>
                                <div class="caption">
                                    <h2>Products</h2>
                                    <p>Our food and services are second to none.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:product_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                                <div class="caption">
                                    <h2>Services</h2>
                                    <p>High quality products at affordable prices.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:service_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

crm/templates/crm/customer_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=customer.cust_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

crm/templates/crm/customer_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}

{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}
</html>

crm/templates/crm/customer_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food Services</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Maverick Food Services, Ingredients For Your Success!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Name</th>
                <th>Organization</th>
                <th>Role</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Bldg-Room</th>
                <th>Account</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_name }}</td>
                    <td>{{ customer.organization }}</td>
                    <td>{{ customer.role }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.phone_number }}</td>
                    <td>{{ customer.bldgroom }}</td>
                    <td>{{ customer.account_number }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td><a href="{% url 'crm:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>

                    <td><a href="{% url 'crm:customer_delete' pk=customer.pk %}"
                        onclick="return confirm('Are you sure you want to delete?')"
                        class="btn btn-danger">Delete</a>
                    </td>

                    <td><a href="{% url 'crm:summary' pk=customer.pk %}"
                           class="btn btn-primary">Summary</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}
</html>

crm/templates/crm/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load static %}
{% block content %}

   <body>
   {% if user.is_authenticated %}
       <div class="page-container">

           <h2 class="top-menu">Hello {{ user.username }},</h2>
           <p>Please choose from below options.</p>

       </div>
   {% endif %}
   <div class="content container">
       <div class="row">
           <div class="col-md-12">
               <div class="links">
                   <!-- Example row of columns -->
                   <div class="row">
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                               <div class="caption">
                                   <h2>Customer</h2>
                                   <p>We see our success in our customers success </p>
                                   <p><a class="btn btn-primary" href="{% url 'crm:customer_list' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>
                               <div class="caption">
                                   <h2>Services</h2>
                                   <p>Great Services</p>
                                   <p><a class="btn btn-primary" href="{% url 'crm:service_list' %}"
                                         role="button">View details &raquo;</a></p>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                               <div class="caption">
                                   <h2>Products</h2>
                                   <p>Great Products.</p>
                                   <p><a class="btn btn-primary" href="{% url 'crm:product_list' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                               </div>
                           </div>
                       </div>

                   </div>
               </div>
           </div>
       </div>
   </div>
   </body>

{% endblock %}

</html>

crm/templates/crm/product_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Delete {{ product.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:service_list' pk=service_category %} ">Cancel</a>

    </form>

{% endblock %}
</html>

crm/templates/crm/product_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

</html>

crm/templates/crm/product_list.html
<!DOCTYPE html>
{% extends 'crm/base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food service</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Maverick Food services, Ingredients For Your Success!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Product Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer</th>
                <th>Product</th>
                <th>Product Description</th>
                <th>Quantity</th>
                <th>Pickup Time</th>
                <th>Charge</th>
                <th>Create Date</th>
                <th>Update Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.cust_name }}</td>
                    <td>{{ product.product }}</td>
                    <td>{{ product.p_description }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>{{ product.pickup_time }}</td>
                    <td>{{ product.charge }}</td>
                    <td>{{ product.create_date }}</td>
                    <td>{{ product.update_date }}</td>
                    <td><a href="{% url 'crm:product_edit' pk=product.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:product_delete' pk=product.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                        class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    <div class="row">
         <a href="{% url 'crm:product_new' %}" class="row"><span
                    class="btn btn-primary">Add Product</span></a>
     </div>

    </body>
{% endblock %}

</html>

crm/templates/crm/product_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Add a New Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>

crm/templates/crm/service_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Delete {{ service.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:service_list' pk=service_category %} ">Cancel</a>

    </form>

{% endblock %}
</html>

crm/templates/crm/service_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit Service</h1>
    <form method="POST" class="service-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

</html>

crm/templates/crm/service_list.html
<!DOCTYPE html>
{% extends 'crm/base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food service</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Maverick Food services, Ingredients For Your Success!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Services Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer</th>
                <th>Service Category</th>
                <th>Description</th>
                <th>Location</th>
                <th>Setup Time</th>
                <th>Cleanup Time</th>
                <th>Service Charge</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for service in services %}
                <tr>
                    <td>{{ service.cust_name }}</td>
                    <td>{{ service.service_category }}</td>
                    <td>{{ service.description }}</td>
                    <td>{{ service.location }}</td>
                    <td>{{ service.setup_time }}</td>
                    <td>{{ service.cleanup_time }}</td>
                    <td>{{ service.service_charge }}</td>
                    <td><a href=""
                           class="btn btn-warning">Edit</a></td>
                    <td><a href=""
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>


    </body>
{% endblock %}

crm/templates/crm/service_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Add a New Service</h1>
    <form method="POST" class="service-form">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>